### ISSUE TITLE
您好，为什么我右侧的深度出不来呢？

### ISSUE THREAD

**Issue by rui092** [chxj1992/kline#11]
![2017-11-27 5 33 41](https://user-images.githubusercontent.com/19640774/33259853-22333c54-d399-11e7-9372-776377a36434.png)

**Comment by chxj1992** [comment]
数据比较少的时候, 深度就出不来

**Comment by chxj1992** [comment]
深度数据比较少的时候就出不来

**Comment by rui092** [comment]
ok,谢谢
