### ISSUE TITLE
底部的具体时间无法显示吗？

### ISSUE THREAD

**Issue by view868** [chxj1992/kline#13]

**Comment by chxj1992** [comment]
底部应该有一个精确到分钟的时间坐标，你的问题是？

**Comment by view868** [comment]
我运行了项目，在鼠标未移动到画布上时，底部是没有时间坐标显示的，但是我看您的截图是有显示的，另外可以发个打赏二维码不 0-0，这个项目真的很有用,感谢！

**Comment by view868** [comment]
另外，在鼠标进入画布的时候也只有一个精准的时间刻度，而没有出现时间坐标，用的也是您的mock.js数据

**Comment by chxj1992** [comment]
我更新了一下mock数据, 发现下面的时间坐标就显示出来了, 怀疑是数据里的时间太老, 就不会显示底部的时间坐标.  我把更新的mock数据提交了, 你可以拉下来看看对不对.

**Comment by chxj1992** [comment]
这个项目也不完全是我本人开发的, 只是做了一些封装和二次开发. 所以也不好意思接受打赏啦, 如果使用遇到问题, 可以及时反馈, 共同解决
