### ISSUE TITLE
请问楼主，除了分时的那个周期外，其他周期数据都是一样的，没有变动，请问从哪可以针对其他周期进行设置？？

### ISSUE THREAD

**Issue by EdenYaoYao** [chxj1992/kline#16]

**Comment by chxj1992** [comment]
选择不同周期的时候, 插件发送的请求参数会有变化, 服务端根据不同参数返回不同数据, mock数据只是个静态文件, 起个数据结构示例的作用,  所以不变化

**Comment by EdenYaoYao** [comment]
哦哦，谢谢楼主

**Comment by EdenYaoYao** [comment]
谢谢楼主

**Comment by EdenYaoYao** [comment]
楼主，不好意思，我还有个问题没弄明白，我分别模拟了分钟阶段和小时阶段的json数据文件，K线图在分钟和小时是变化的，但是我该如何动态的点击调用不同的json数据文件呢？还是说该怎么样？

**Comment by chxj1992** [comment]
这个需要在服务端做一些开发, 来实现根据不同的请求参数返回不同的数据
