### ISSUE TITLE
socket 必须使用http,https吗？

### ISSUE THREAD

**Issue by jsoncode** [chxj1992/kline#2]
配置了之后：
```
{
    type:'socket',
    url:'http://loalhost/a/',
    subscribePath: "/kline/push",
    sendPath: "/app/kline",
}
```
socket请求地址确是：http://localhost/a/info?......这个info哪来的？这个socket为什么不是ws/wss协议？
我改成ws://localhost会报错the URL's scheme must be either 'http:' or 'https:'. 'ws:' is not allowed

**Comment by chxj1992** [comment]
@jsoncode  kline默认使用了sockjs作为websocket客户端以实现在不支持websocket的浏览器上实现自动降级方案, 不过这也需要服务端提供支持, 大概的逻辑是实现一个 xxx/info 接口返回服务端的连接信息, sockjs客户端再根据这个信息向服务端请求数据, 有些后端框架提供了对sockjs的支持.  目前kline(1.0.9)已经提供了 enableSockjs 参数, 默认是true,  如果修改为 false, 则不使用sockjs, 而是直接使用stomp客户端建立websocket连接, 这样就不会出现你遇到的问题了
