### ISSUE TITLE
用socket链接出错了，请问这个是什么原因啊

### ISSUE THREAD

**Issue by gj201314** [chxj1992/kline#21]
sockjs.js:sourcemap:682 Uncaught SyntaxError: The URL's scheme must be either 'http:' or 'https:'. 'ws:' is not allowed.

**Comment by chxj1992** [comment]
默认会使用sockjs方式进行连接，所以要求一个http地址，可以把enableSockjs设置为false来避免。另外，服务端需要支持stomp子协议，而不仅仅是单纯的websocket(在kline1.1之后的版本中，type参数里的socket改成了stomp以减少歧义)

**Comment by gj201314** [comment]
恩，好的，谢谢您，我还有几个问题，想请您帮忙解答一下。https://kline-1f82d.firebaseio.com/.lp?start=t&ser=47115211&cb=7&v=5  这个好像是个js文件，一直在请求，可以去掉吗？还有接口的数据格式在哪调整？从后端请求过来的数据和插件要求的数据格式不同，我想调整一下，麻烦您有时间了解答一下，谢谢您

**Comment by chxj1992** [comment]
firebase那个是个打点数据采集, 可以在src/js/kline.js里取消引用然后重新打包.  src/js/control.js 里有个 requestSuccessHandler 方法, 可以在该方法中将服务端返回的数据结构格式化成插件需要的数据结构

**Comment by gj201314** [comment]
多谢您的解答，我抽时间试试，如果过程中发现新的问题，还请您有时间的时候帮我看一下，谢谢

**Comment by chxj1992** [comment]
嗯,没问题
