### ISSUE TITLE
时不时有一个请求 firebaseio.com，没看明白这个是什么作用？

### ISSUE THREAD

**Issue by kamixueti** [chxj1992/kline#25]
过一段时间就会有一个如下的请求，没看明白这个是干啥的？而且这个地址打不开。
https://kline-1f82d.firebaseio.com/.lp?start=t&ser=89034133&cb=19&v=5

**Comment by chxj1992** [comment]
是一个打点数据, 1.1.5版本之后, 可以设置 disableFirebase: true,  禁止该请求

**Comment by kamixueti** [comment]
知道了。谢谢。
