### ISSUE TITLE
有添加蝴蝶图的计划吗？

### ISSUE THREAD

**Issue by jsoncode** [chxj1992/kline#3]
这个图几乎和ok的一样，但是没有蝴蝶图，不知道有没有这方面的计划。
我把你的kline改写了一下，去掉了socket.js,stomp.js，添加了几行原生的websocket js代码，kline.js还没有完全优化完毕。感觉这样更精简了

**Comment by chxj1992** [comment]
暂时没有计划, 自行fork实现哈
