### ISSUE TITLE
 SockJS is not defined

### ISSUE THREAD

**Issue by MrYuSen-Liu** [chxj1992/kline#32]
为什么还会报这个错
![image](https://user-images.githubusercontent.com/25242149/36336859-ee14b646-13c6-11e8-95c3-3d75f2edebe5.png)

**Comment by chxj1992** [comment]
stomp方式 需要引入 [sockjs](https://www.npmjs.com/package/sockjs) 和 [stompjs](https://www.npmjs.com/package/stompjs) 这两个库

**Comment by DemoHu** [comment]
@chxj1992   你好，我是在vue中使用的kline， 直接npm install kline
npm获得的包里面没有sockjs和stompjs 这两个文件，请问怎么处理
