### ISSUE TITLE
后端返回来的数据格式想要用平时的json格式可以吗 ？需要怎么修改呢

### ISSUE THREAD

**Issue by lzj3823** [chxj1992/kline#36]

**Comment by chxj1992** [comment]
目前确实是json格式的, 具体是指哪里?

**Comment by lzj3823** [comment]
谢谢你的回答哈。"lines": [
            [
                1.5121452E12,
                91.29,
                91.29,
                91.29,
                91.29,
                0.0
            ]]  ，就是这里我看了一下你的数据 结构是这个，那我后端要是返回跟你插件mock.json里面的  "trades": [
            {
                "amount": 19.79,
                "price": 100.92,
                "tid": 1585662041877811201,
                "time": 1512205163878,
                "type": "sell"
            }]    一样的结构（字段不一样哈），也是可以修改的是吗？

**Comment by chxj1992** [comment]
你比较的其实是一份数据的不同部分,  每组数据包括 "lines", "trades", "depths" 三项,   分别对应K线, 成交列表 和 深度图,  详细说明可参看文档
