### ISSUE TITLE
关于数据改变视图不更新的问题

### ISSUE THREAD

**Issue by coinsuper** [chxj1992/kline#39]
开发过程中遇到数据已经发生改变视图不更新的问题，大致有如下两个问题
1.自动刷新几分钟后不会再进行刷新，ajax请求回来的数据有更新。
2.假如当前选择一分钟线，成交量是0，在这一分钟内发生了成交，成交量改为20，此时视图不会更新，且会造成后续视图一直不会再刷。
以上两种情况数据都可以正常返回，想问一下有什么解决办法啊，我试了重新去执行kline.draw()还是不会刷新。

**Comment by coinsuper** [comment]
已修复，后台数据问题

**Comment by chenjiejing** [comment]
请问下,如果点击一分钟,两分钟这些按钮需要传参吗?我也遇到视图不更新的问题,后台能返回数据,但是需要刷新页面才发现视图有改变

**Comment by gyj19890413** [comment]
> 请问下,如果点击一分钟,两分钟这些按钮需要传参吗?我也遇到视图不更新的问题,后台能返回数据,但是需要刷新页面才发现视图有改变

怎么获取前面的数据啊      后台只给了1000条数据      往前面拉的时候   拉到最前面   然后获取前一段时间的数据   并渲染     这个问题怎么解决

**Comment by chenjiejing** [comment]
这个跟后台返回的数据有关吗?如果后台返回的随机数是变化不大的数,那么是不是视图会不跟新?
