### ISSUE TITLE
在vue组件中url不管怎么写都无法展示数据。

### ISSUE THREAD

**Issue by yurokn** [chxj1992/kline#43]
在vue组件中引入插件，别的都能显示，但是 
不管url: "mock.json"
或 url: "http://127.0.0.1:8080/mock.json" 都无法展示出数据。

**Comment by chxj1992** [comment]
mock.json只是个数据格式样例，要请求服务端接口

**Comment by yurokn** [comment]
我用koa自荐了一个服务器 localhost:3000返回json中的内容,还是不行啊，浏览器调试显示请求的是kine-***的地址，而不是localhost:3000.
________________________________
发件人: Xiaojing CHEN <notifications@github.com>
发送时间: 2018年3月26日 13:40:16
收件人: chxj1992/kline
抄送: yurokn; Author
主题: Re: [chxj1992/kline] 在vue组件中url不管怎么写都无法展示数据。 (#43)


mock.json只是个数据格式样例，要请求服务端接口

―

**Comment by yurokn** [comment]
问题搞定了，谢谢作者。
