### ISSUE TITLE
k线 图红绿颜色设置反了

### ISSUE THREAD

**Issue by CJ921008** [chxj1992/kline#5]
我只传了lines参数,发现 k线图上红绿颜色反了 在哪里可以设置吗
![image](https://user-images.githubusercontent.com/20183855/32173059-a8ac2c74-bdb8-11e7-93af-5f05a9818c43.png)

**Comment by chxj1992** [comment]
默认采用了国际更通用的绿涨红跌(和国内习惯正好相反), 在 1.0.11 版本中新增了 reverseColor 属性, 把reverseColor设置为true即可

**Comment by jsoncode** [comment]
绿涨红跌是对的，不知道为毛国内搞一个红涨绿跌，红，表示危险，danger,绿表示成功，希望。

**Comment by chxj1992** [comment]
应该是因为国内红表示喜庆吧，哈哈哈
