### ISSUE TITLE
为什么kline.js正常使用的时候一直在请求这个地址？如何把这个请求去掉？

### ISSUE THREAD

**Issue by yurokn** [chxj1992/kline#51]
![default](https://user-images.githubusercontent.com/16041033/38767387-d83805bc-4012-11e8-9e1d-a2b99efe1110.PNG)

**Comment by kamixueti** [comment]
在配置里边添加这个。
disableFirebase: true

**Comment by yurokn** [comment]
牛逼，感谢。这样我就不用在源码里改了。文档里找了半天也没有找出这个api.
