### ISSUE TITLE
kline有时候可以用鼠标滚轮缩小，但无发放大！

### ISSUE THREAD

**Issue by yurokn** [chxj1992/kline#54]

**Comment by hahaet** [comment]
遇到了相同的问题，请问有解决吗

**Comment by DemoHu** [comment]
我也是这个问题，请问解决了么

**Comment by DemoHu** [comment]
@hahaet  你好，请问你解决了这个问题了么

**Comment by xwm0660** [comment]
这个问题是 没有正确引入mousewheel 的js文件  引入正确就OK了

**Comment by boyixiang** [comment]
请问下怎么引入这个到项目中

**Comment by chenjiejing** [comment]
import kline form kline 包是引入了的全部东西的意思吗?

**Comment by chenjiejing** [comment]
昨天解决了这个问题,npm install jquery-mousewheel,然后在main.js 引入require('jquery-mousewheel'),之前一直引入包里的js文件都不起作用

**Comment by xuechunpeng01** [comment]
> 这个问题是 没有正确引入mousewheel 的js文件 引入正确就OK了

请问怎么算正确引入，我安装了jQ并在webpack的配置文件配置了，在组件里引用，$可以正常使用，但是kline一直报错ReferenceError: $ is not defined"，请问怎么解决

**Comment by yurokn** [comment]
关闭
