### ISSUE TITLE
请问在第一次渲染完成之后，如何更新数据（生成新的k线柱和刷新最后一根k线柱子）？

### ISSUE THREAD

**Issue by wangwei8888** [chxj1992/kline#55]
我们的需求是这样的，后台socket第一次推送1000条数据，之后每次都只推送1条最新的数据。要求能做到:
1.刷新最后1根k线柱子
2.在所有柱子后面新增1条最新的k线柱子.
需求1已经实现了；
需求2 目前的解决办法是直接往 kline.instance.data 里面push 最新的数据， 但是会出现很多问题
请问内核是否有提供新增k线柱子的方法。或者根本不用手动去push最新的数据，内核自己会自动增加k线柱子。
请大牛不吝赐教，小弟感激不尽 @chxj1992

**Comment by chxj1992** [comment]
K线每组数据的第一列是聚合后的时间戳, 目前的实现应该以时间戳为X轴, 如果是新增数据就放在对应的位置, 如果是老数据就替换掉, 所以你的需求应该都是已经实现了的

**Comment by f056917** [comment]
@wangwei8888 请问这个问题解决了吗？方便告知一下解决方法吗？感谢！！
