### ISSUE TITLE
1分钟线数据显示有问题

### ISSUE THREAD

**Issue by wangwei8888** [chxj1992/kline#57]
后台返回的数据价格为310，但是k线的1分钟线 显示成了31.   如图suo'shi所示，其他的5分钟10分钟等都是正常的。找了很久不 知道是什么原因，不知道大家有没有遇到这个问题
![image](https://user-images.githubusercontent.com/36029972/39423012-8e434240-4ca2-11e8-9c37-30e767eaf65c.png)

**Comment by yumengzhi** [comment]
同样遇见这个问题，跟你描述的一毛一样。数据追踪到Kline.js中，有时成交的瞬间，判定返回数据未更新。之后每次获取新数据都不会再更新视图了，除非刷新页面。但是返回数据中明明加了时间戳。
