### ISSUE TITLE
求API

### ISSUE THREAD

**Issue by leefj** [chxj1992/kline#62]
可否增加以下API
1、移动到指定位置的方法，如  kline.moveTo("20180403") 或 kline.moveTo(16)  这里的16是一个序号
2、给某一区间设置背景色，如 kline.setSpanColor("20180403","20180506","#ff0000");

**Comment by chxj1992** [comment]
最近比较忙, 可能没时间维护这个项目了, 如果有需求, 建议fork后自行修改哦
