### ISSUE TITLE
是否把行情数据存在了cookie中

### ISSUE THREAD

**Issue by CJ921008** [chxj1992/kline#7]

**Comment by CJ921008** [comment]
我把源码改了一下,能够分别获取深市和沪市的不同的详情,但是当我获取沪市的股票返回去重新选择深市的股票,详情还是沪市的内容. 比如选择了 000002的沪市 A股指数,再返回去重新选择 000002的深市的万科A. 详情还是沪市A股指数的内容 .请问哪里可以修改一下.谢谢

**Comment by chxj1992** [comment]
应该没有, 打断点分析一下吧, 看看是不是更新数据后图表没有重画
