### ISSUE TITLE
您好，我想请问一下该插件该怎么去除volume的显示?默认是展示volume，有没有什么方法可以不显示volume吗

### ISSUE THREAD

**Issue by HEJIN2016** [chxj1992/kline#8]

**Comment by chxj1992** [comment]
<img width="318" alt="screen shot 2017-11-23 at 11 04 03 am" src="https://user-images.githubusercontent.com/1113743/33157591-3241f954-d03e-11e7-96d8-158f7285598a.png">
5423行有个叫 displayVolume 的属性, 改成 false 就行了

**Comment by chxj1992** [comment]
先自己fork去改改好了 哈哈
