### ISSUE TITLE
多谢了。还想问一下，这个插件有办法销毁实例吗？比如我要在不同的交易对切换，需要销毁·原来的画的k线图，我直接设置新的请求路径并调用kline.resend()时，接口是调用了，但界面上显示的有问题，上一个kline实例的数据还是在现在的实例上。这个问题有办法解决吗？

### ISSUE THREAD

**Issue by HEJIN2016** [chxj1992/kline#9]
多谢了。还想问一下，这个插件有办法销毁实例吗？比如我要在不同的交易对切换，需要销毁·原来的画的k线图，我直接设置新的请求路径并调用kline.resend()时，接口是调用了，但界面上显示的有问题，上一个kline实例的数据还是在现在的实例上。这个问题有办法解决吗？

**Comment by chxj1992** [comment]
可以第二个交易返回全量数据把之前的覆盖掉

**Comment by chxj1992** [comment]
ps.  切换请求的时候, K线实例修改url属性就行了, 其实不用调用resend

**Comment by HEJIN2016** [comment]
怎么覆盖呢。我把原来的kline.data清空没有用，将整个div empty掉，然后将kline = null，都没有作用。切换之后显示的还是上一个数据源的图

**Comment by HEJIN2016** [comment]
我找到原因是我切换的时候还会请求一次原来的地址，但不知道怎么解决这个问题

**Comment by HEJIN2016** [comment]
kline = new Kline({
				element: "#kline_container",
				width: 1400,
				height: 600,
				theme: 'dark', // light/dark
				language: 'zh-cn', // zh-cn/en-us/zh-tw
				ranges: ["1w", "1d", "1h", "30m", "15m", "5m", "1m", "line"],
				symbol: "coin5/coin4",
				symbolName: "COIN5_COIN4",
				type: "poll", // poll/socket
				url: url,
				limit: 1000,
				intervalTime: 5000,
				debug: true,
				showTrade: false,
				onResize: function (width, height) {
					console.log("chart resized: " + width + " " + height);
				},
				onRangeChange: function (range) {
					if (range == 604800000) {
						space_time = 30 * 7;
						period = 'week';
					} else if(range == 86400000){
						space_time = 30;
						period = 'day';
					} else if(range == 3600000){
						period = 'hour';
					} else if(range == 1800000){
						period = '30mins';
					} else if(range == 900000){
						period = '15mins';
					} else if (range == 300000) {
						period = '5mins';
					} else if(range == 60000){
						period = 'min';
					}
					var obj = {
						exchange: exchange,
						currency: coin,
						time: (new Date().getTime() - 86400000 * space_time + gapTime)/1000,
						period: period
					};
					console.log(obj);
					var params = $.param(obj);
					kline.url = CONFIG.URL + 'k2/?' + params;
				}
			});
			kline.draw();

**Comment by chxj1992** [comment]
可能是个bug，你可以查一下问题，然后给我 pull request

**Comment by HEJIN2016** [comment]
那这个插件有办法设置默认的k线类型吗？比如默认设为5分钟k线。他的默认k线好像一直在变，跟cookie有关

**Comment by chxj1992** [comment]
默认的应该是你上次看的类型,  cookie里有一项 chartSettings 可以看一眼

**Comment by f056917** [comment]
@HEJIN2016 请问这个问题解决了吗？我也遇到了同样的问题，但是找了两天没有解决，方便帮下忙吗？谢谢啦！

**Comment by HEJIN2016** [comment]
> @HEJIN2016 请问这个问题解决了吗？我也遇到了同样的问题，但是找了两天没有解决，方便帮下忙吗？谢谢啦！

没有解决，我后面是嵌入了一个iframe，改变iframe路径，就会销毁

**Comment by f056917** [comment]
> > @HEJIN2016 请问这个问题解决了吗？我也遇到了同样的问题，但是找了两天没有解决，方便帮下忙吗？谢谢啦！
> 
> 没有解决，我后面是嵌入了一个iframe，改变iframe路径，就会销毁

我想到另一个办法，你可以看看https://github.com/chxj1992/kline/issues/96#issue-393858717
