### ISSUE TITLE
请问为什么要在项目里面集成firebase？ 集成了有什么用？

### ISSUE THREAD

**Issue by yesongling** [chxj1992/kline#90]

**Comment by chenjiejing** [comment]
你能在vue里面渲染图表吗?

**Comment by yesongling** [comment]
> 你能在vue里面渲染图表吗?

可以

**Comment by chenjiejing** [comment]
请问你有遇到轮询的时候,后台返回随机数,k线图不会动的情况吗?

**Comment by yesongling** [comment]
没有 他这个插件拿下来 为了能对接我们自己的接口 我改了很多东西

**Comment by yesongling** [comment]
> 请问你有遇到轮询的时候,后台返回随机数,k线图不会动的情况吗?

没有 除非自己的数据接口每次返回的数据本身就没有什么变动

**Comment by chenjiejing** [comment]
@yesongling 能否加下qq或者微信13535046199
